s=' Welcome To Python '
print(s)
print('s.lower()',s.lower())
print('s.upper()',s.upper())
print('s.title()',s.title())
print('s.capitalize()',s.capitalize())
print('s.swapcase()',s.swapcase())
print('s.isalpha()',s.isalpha())
print('s.isdigit()',s.isdigit())
print('s.islower()',s.islower())
print('s.isupper()',s.isupper())
print('s.isspace()',s.isspace())
print('s.startswith("welcome")',s.startswith('welcome'))
print('s.endswith("n")',s.endswith('n'))
print('s.find("To")',s.find('To'))
print('s.index("TO")',s.index('To'))
#print('s.index("TO")',s.index('to')) # if to not in string it is show error
print('s.count("TO")',s.count("To"))
print('s.replace("Python","Java")',s.replace('Python','Java'))
print('s.strip()',s.strip())
print('s.lstrip()',s.lstrip())
print('s.rstrip()',s.rstrip())
print('s.split()',s.split())

